"""add shots to games

Revision ID: 5df56f386918
Revises: 7242ea7fb968
Create Date: 2026-09-21 22:44:32.036502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df56f386918'
down_revision: Union[str, Sequence[str], None] = '7242ea7fb968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'games',
        sa.Column(
            'shots',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'shots')
    # ### end Alembic commands ###
