"""add closed to games

Revision ID: 9bfe98377637
Revises: 5df56f386918
Create Date: 2026-10-01 01:12:17.590490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfe98377637'
down_revision: Union[str, Sequence[str], None] = '5df56f386918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'games',
        sa.Column(
            'closed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'closed')
    # ### end Alembic commands ###
